### PR TITLE
Updated version of the balance scheme

### PR DESCRIPTION
**Pull request by jeankpf**
Hello there,

I need an updated version of the balance scheme for some numerical linear analysis (in order to later couple this with a python file for initialising the flow with specific, non-trivial eigenmodes). So I started from the last master branch on the idefix repo and cherry-picked the few commits I needed from the balanceScheme branch. Obviously in doing it is not possible to automatically merge my changes to the current balanceScheme branch. I think that the simplest way to proceed would be to directly overwrite the current branch with my updated one. Let me know what you think of this.

Note that in order to compile the code after cherry-picking the few commits, I needed for some reasons to revert the signature of two functions from the class Dump, namely read and write, from Read(Output&, int) and Write(&Output), to Read(int) and Write(), respectively. I don't understand why the signature of these functions has changed with the new IDEFIX version, because the Output instance doesn't seem to be used in the functions at the time being. Are you planning something for the future version?

### CODE REVIEW

**Comment by neutrinoceros** [comment]
@jeankpf you may need to rebase this branch to resolve the conflicting histories. Let me know if you need a hand !

**Comment by glesur** [comment]
The reference to Output in the dump class was required in idefix 1.0 but it not needed anymore, so this should be clean up.

On the cherry-pick, I agree with @neutrinoceros , this should be rebased.

**Comment by jeankpf** [comment]
Hi @neutrinoceros, thanks for your message. Actually, I would be very interested in knowing what are good practices in this particular case. It seems to me that the commit on top of which the balanceScheme branch is currently build was in the history of the master branch at some point. But since then, I think part of the history of the master branch has been rewritten, and it is no longer straigthforward to rebase the current balanceScheme branch. I tried to, but it looked like a very tedious task, because of this history confict between an old and the current master branch. I hope I am clear, but please let me know if I'm talking bollocks.

**Comment by jeankpf** [comment]
Ok, I think I will go for a rebase at some point then, but maybe not today. Thanks!

**Comment by neutrinoceros** [comment]
FTR, we had a chat with @jeankpf yesterday and the situation as I understand it is:
- The `balanceScheme` branch is way out of date and was branched out from `master` before 2022´s Great Rewrite, so it's absolutely unmergeable at this point.
- in order to bring this work back to life, the simplest approach is to cherry-pick the 5 last commits from that branch into a new branch from master and cleanup compatibility issues in a sixth commit, which is precisely what Jean did in the branch attached to this PR

What I suggest we do is:
- close this PR
- move `updatedBalanceScheme` from Jean's fork to the mother repo
- remove the original branch from the mother repo as it's rotted and not needed anymore.

I think I have sufficient permissions on the repo to perform every step myself, but let me ask for @glesur's blessing first.

**Comment by glesur** [comment]
@neutrinoceros : feel free to close this PR and rebase this module. Note however that I do not intend to merge this into master anytime, the reason being that the method is fishy as gives you the wrong impression that the scheme ends up being balanced, while it just restores a numerical equilibrium by removing some residual on the RHS.

I'm pretty convinced that in some situation it might not even capture the correct linear dynamics, and so I do not want people to use this feature blindly (as this happens quite often). @jeankpf has been warned in that respect (but I think it should work for his particular application).

**Comment by neutrinoceros** [comment]
Understood ! I'll try to do it on the train I'm about to board.

**Comment by neutrinoceros** [comment]
@jeankpf I just pushed you branch to this repo
(I also accidentally pushed to your fork FYI)
@geoff I'll close this PR now. I also strongly suggest to remove the original `balanceScheme` branch from this repo, though I'd prefer to wait for confirmation that I didn't mess things up before that.

**Comment by jeankpf** [comment]
Great, thank you very much for your help! Cheers

**Pull request closed without merging**
